### ISSUE TITLE
Client will not start

### ISSUE THREAD

**Issue by SmilerRyan** [zenith110/Toontown_Server#11]
There appears to be a memory allocation error when trying to launch the client.
The allocation that failed (according to the code) is ~400MB.
I have over 4GB of RAM free (which this project can use).

The memory for the process:
    PPython elevates to ~700MB in usage.
    Command Prompt elevates to ~150MB usage.
    PPython goes down to ~10MB and stops responding.

Here is the script I am using:

    @echo off
    set /P PPYTHON_PATH=<DEV\backend\PPYTHON_PATH
    
    set input=1
    set ttiUsername=TEST
    set TTI_PLAYCOOKIE=TEST
    set TTI_GAMESERVER=127.0.0.1
    
    set ttiPassword=password
    
    %PPYTHON_PATH% -m toontown.toonbase.ToontownStart
    pause

And here is the log I am receiving:

    Warning: pandac.PandaModules is deprecated, import from panda3d.core instead
    :ToontownStart: Reading user/preferences.json...
    :ToontownStart: Starting the game...
    :ToontownStart: Setting the default font...
    TTLocalizer: Running in language: English
    OTPLocalizer: Running in language: English
    Known pipe types:
      wglGraphicsPipe
    (2 aux display modules not yet loaded.)
    :ToonBase: Default graphics pipe is wglGraphicsPipe (OpenGL).
    :display:windisplay(warning): Could not find cursor filename phase_3/etc/toonmono.cur
    :display:windisplay(warning): Could not find cursor filename phase_3/etc/toonmono.cur
    :ToonBase: Successfully opened window of type wglGraphicsWindow (OpenGL)
    :ShowBase: __dev__ == False
    Out of memory allocating 402653192 bytes
    AL lib: (EE) alc_cleanup: 1 device not closed
    Press any key to continue . . .

**Comment by zenith110** [comment]
Howdy, there's a launcher.py within the folder. No need to make a .bat script as the launcher.py will instead handle user interaction. 

Make sure to grab the appropriate imports that are specified. 

Thank you.

**Comment by SmilerRyan** [comment]
I only used this batch file (code from the launcher.py) so I don't have to re-enter these fields every time.
If I launch the launcher.py file directly with the properties (TEST, localhost, ppython path), the console still shows the same problem.

**Comment by zenith110** [comment]
Have you installed all the dependencies and a fresh copy of the server? I had checked running the .py alone and seem to not be having any issues. I think the issue may arise from the resource folder, so try downloading it again. Thank you for your patience.

Also I've noticed you tried to use TTI enviroment variables and try to use set the ppython path to a file, you'll need to set the TTS enviroment and not TTI as this is built off stride.

**Comment by SmilerRyan** [comment]
I have now re-downloaded the latest version ([4d6a042](https://github.com/zenith110/Toontown_Server/commit/4d6a04293c17269ffe1524bb54b1bfa2aadb0334)), and the source now simply works.
Also, using the batch file now works after realising that I was using the wrong environment variables.
